# Generated by Django 3.2.8 on 2021-10-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
