# Generated by Django 3.2.8 on 2021-10-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identity',
            field=models.IntegerField(max_length=80, null=True),
        ),
    ]
