# Generated by Django 3.2.8 on 2021-10-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour_app', '0002_alter_profile_occupants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hood',
            field=models.CharField(default='mtaa yako', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identity',
            field=models.IntegerField(default='12345678', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='areacode', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupants',
            field=models.IntegerField(blank=True, default='5000', null=True),
        ),
    ]
