# Generated by Django 3.2.8 on 2021-10-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour_app', '0003_auto_20211030_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.IntegerField(blank=True, default='5000', null=True),
        ),
    ]
