# Generated by Django 3.2.8 on 2021-10-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour_app', '0007_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
