# Generated by Django 3.2.8 on 2021-10-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour_app', '0011_auto_20211029_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
